name: Deploy

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/github-script@v7
        with:
          script: |
            await require("./.github/download-artifacts.cjs").call(context, github, {
              outdir: "${{ runner.temp }}/artifacts",
            });

      - name: Unzip build artifacts
        run: unzip dist.zip -d "${{ runner.temp }}/artifacts"

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload build artifacts to AWS S3
        run: |
          aws s3 sync dist s3://${{ vars.AWS_S3_BUCKET_NAME }} --delete
